# Generated by Django 5.2.4 on 2025-08-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_gradeseries_expected_publish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeapplication",
            name="participant_current_grade",
            field=models.CharField(
                choices=[
                    ("5", "absolvent"),
                    ("4", "SŠ, 4."),
                    ("3", "SŠ, 3."),
                    ("2", "SŠ, 2."),
                    ("1", "SŠ, 1."),
                    ("0", "ZŠ, 9."),
                    ("-1", "ZŠ, 8."),
                    ("-2", "ZŠ, 7."),
                    ("-3", "ZŠ, 6."),
                ],
                max_length=10,
                null=True,
                verbose_name="Ročník",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="school_year",
            field=models.CharField(
                choices=[
                    ("5", "absolvent"),
                    ("4", "SŠ, 4."),
                    ("3", "SŠ, 3."),
                    ("2", "SŠ, 2."),
                    ("1", "SŠ, 1."),
                    ("0", "ZŠ, 9."),
                    ("-1", "ZŠ, 8."),
                    ("-2", "ZŠ, 7."),
                    ("-3", "ZŠ, 6."),
                ],
                max_length=5,
                verbose_name="Ročník",
            ),
        ),
    ]
