# Generated by Django 5.2.11 on 2026-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_stickers_improvement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Podporuje formátování Markdown (tučné písmo, kurzíva, odkazy).",
                        verbose_name="Zpráva oznámení",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("info", "Informace (modrá)"),
                            ("warning", "Varování (žlutá / oranžová)"),
                            ("danger", "Důležité upozornění (červená)"),
                            ("success", "Úspěch (zelená)"),
                            ("neutral", "Neutrální (světle šedá)"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Barevný styl",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Zaškrtněte pro zobrazení oznámení na webu.",
                        verbose_name="Aktivní",
                    ),
                ),
                (
                    "only_authenticated",
                    models.BooleanField(
                        default=False,
                        help_text="Pokud je zaškrtnuto, banner se zobrazí pouze přihlášeným uživatelům.",
                        verbose_name="Pouze pro přihlášené uživatele",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Volitelné. Ponechte prázdné pro okamžité zobrazení.",
                        null=True,
                        verbose_name="Zobrazovat od",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Volitelné. Ponechte prázdné pro neomezenou platnost.",
                        null=True,
                        verbose_name="Zobrazovat do",
                    ),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Uživatel si může banner skrýt kliknutím na křížek.",
                        verbose_name="Lze skrýt křížkem",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Volitelné. Např. '/akce/' nebo celá URL.",
                        max_length=255,
                        verbose_name="Odkaz tlačítka (URL)",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Např. 'Více informací' nebo 'Přejít na přihlášku'.",
                        max_length=100,
                        verbose_name="Text tlačítka",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
            ],
            options={
                "verbose_name": "Oznámení (banner)",
                "verbose_name_plural": "Oznámení (bannery)",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="participant",
            name="country",
            field=models.CharField(
                choices=[
                    ("other", "-- jiný --"),
                    ("cz", "Česká republika"),
                    ("sk", "Slovensko"),
                ],
                max_length=10,
                verbose_name="Stát",
            ),
        ),
    ]
