name: Docker Build & Push

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  build-test-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. checkout
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. setup docker buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. cache docker layers
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      # 4. setup node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 22.16.0
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: package-lock.json

      # 5. build assets [TODO]
      - name: Build Assets
        run: |
          .\node_modules\.bin\webpack --config webpack.config.js --mode production


      # 6. login to docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. build and push image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
      
